language: node_js
node_js:
- 8.9.0
cache:
  directories:
  - node_modules
before_install:
- npm install hexo-cli -g
install:
- npm install
script:
- hexo clean
- hexo generate
after_script:
  - cd ./public
  - git init
  - git config user.name "LyneLiu"
  - git config user.email "595596226@qq.com"
  - git add .
  - git commit -m "TravisCI 自动部署"
  # Github Pages
  # - git push --force --quiet "https://${CI_TOKEN}@${GH_REF}" master:master 
  # Coding Pages
  # - git push --force --quiet "https://lyneliu:${CO_TOKEN}@${CO_REF}" master:master
  # Gitee Pages
  - git push --force --quiet "https://${GITEE_TOKEN}@gitee.com:.lyne/lyne.git" master:master
branches:
  only:
  - master 

env:
 global:
   # Github Pages
   # - GH_REF: github.com/LyneLiu/lyneliu.github.io  这里替换你的github仓库地址
   # Coding Pages
   # - CO_REF: git@git.dev.tencent.com:lyneliu/lyneliu.git